### PR TITLE
feat: add error interface to common interfaces

### PR DESCRIPTION
**Pull request by james-a-morris**
This PR adds the new relayer Error interface into the SDK

### CODE REVIEW

**Review by pxrl — COMMENTED** [review]
Thoughts on also adding the isEthersError predicate from TransactionUtils.ts? It's a handy companion utility.

```
const isEthersError = (error?: unknown): error is EthersError =>
    (error as EthersError)?.code in ethers.utils.Logger.errors;
```

**Comment by james-a-morris** [comment]
> d30daf6

Fair point! Added it here: https://github.com/across-protocol/sdk-v2/pull/163/commits/d30daf6611945df0a02b5a592acc67224ca094c6

**Comment by james-a-morris** [comment]
> Thoughts on also adding the isEthersError predicate from TransactionUtils.ts? It's a handy companion utility.
> 
> ```
> const isEthersError = (error?: unknown): error is EthersError =>
>     (error as EthersError)?.code in ethers.utils.Logger.errors;
> ```
> 
> Not sure exactly where it should go; I guess src/interfaces seems to be mostly reserved for type and interface definitions, rather than code. wdyt?

Fair point! Added it here: https://github.com/across-protocol/sdk-v2/pull/163/commits/d30daf6611945df0a02b5a592acc67224ca094c6

**Review by pxrl — APPROVED** [review]
Great!

**Pull request merged**
